# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
     types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: deploy to nuget
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: publish Abstract
      id: publish_nuget_abstract
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/ScriptDotNet.Abstract/ScriptDotNet.Abstract.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: false
        
    - name: publish Network
      id: publish_nuget_network
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/ScriptDotNet.Network/ScriptDotNet.Network.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: false
    
    - name: publish Core
      id: publish_nuget_core
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/ScriptDotNet.Core/ScriptDotNet.Core.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: false
